# -*- coding: utf-8 -*-
"""2ndLowesGrade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQK4-NjyCLwoJ-9lX9ftv458uDeQA-_i
"""

if __name__ == '__main__':
    names = []
    scores = []
    info = []

    for s in range(int(input())):
        name = input()
        score = float(input())
        names.append(name)
        scores.append(score)   # ✅ fixed
        info.append([name, score])

sorted_info = sorted(info, key=lambda x: x[1])
    scores_only = [item[1] for item in sorted_info]
    unique_scores = sorted(list(set(scores)))
    #print(unique_scores)
    if len(unique_scores) < 2:
        second_lowest_score = None
    else:
        second_lowest_score = unique_scores[1]
    #print(second_lowest_score)
    second_lowest_students = []
    for student_info in sorted_info:
        if student_info[1] == second_lowest_score:
            second_lowest_students.append(student_info[0])
    #print(second_lowest_students)
    second_lowest_students.sort()
    for name in second_lowest_students:
        print(name)

if __name__ == '__main__':
    names = []
    scores = []
    info = []

    for s in range(int(input("Enter Number Of Students:"))):
        name = input("Enter Name Of Student:")
        score = float(input("Enter Score Of Student:"))
        names.append(name)
        scores.append(score)
        info.append([name, score])

    sorted_info = sorted(info, key=lambda x: x[1])
    scores_only = [item[1] for item in sorted_info]
    unique_scores = sorted(list(set(scores)))
    #print(unique_scores)
    if len(unique_scores) < 2:
        second_lowest_score = None
    else:
        second_lowest_score = unique_scores[1]
    #print(second_lowest_score)
    second_lowest_students = []
    for student_info in sorted_info:
        if student_info[1] == second_lowest_score:
            second_lowest_students.append(student_info[0])
    #print(second_lowest_students)
    second_lowest_students.sort()
    for name in second_lowest_students:
        print(name)